dist: trusty
sudo: false
addons:
  apt:
    packages:
      - google-chrome-unstable
language: node_js
node_js:
  - "stable"
script: google-chrome --headless --remote-debugging-port=9222 --disable-gpu https://chromium.org
